nls:
  image: globalfoodbook/nls
  volumes:
    - "/home/core/app/nutrition_service:/go/src/nutrition_service"
  restart: always
  container_name: nls
  environment:
    POSTGRES_DB: ${POSTGRES_DB}
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_IP: ${POSTGRES_IP}
  restart: always
redis:
  image: redis
  container_name: redis
  ports:
    - "6379"
  restart: always
mariadb:
  image: mariadb
  container_name: mariadb
  ports:
    - "3306"
  environment:
    MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    MARIADB_USER: ${MARIADB_USER}
    MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    MARIADB_DATABASE: ${MARIADB_DATABASE}
  volumes:
    - "/home/core/app/dumps:/dumps"
  restart: always
ranger:
  image: globalfoodbook/ranger
  container_name: ranger
  links:
    - mariadb
    - redis
  environment:
    AWS_S3: ${AWS_S3}
  volumes:
    - "/home/core/app/dumps:/dumps"
  cap_add:
    - MKNOD
    - SYS_ADMIN
  devices:
    - "/dev/fuse"
  privileged: true
  restart: always
gfb:
  image: globalfoodbook/gfb
  container_name: gfb
  ports:
    - "5118:5118"
  links:
    - mariadb
    - redis
    - nls
  environment:
    AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  volumes:
    - "/home/core/app:/home/gfb/app"
  restart: always
varnish:
  image: globalfoodbook/varnish
  container_name: varnish
  ports:
    - "80:80"
  links:
    - gfb:backend
  environment:
    VARNISH_HOST: globalfoodbook.com
  restart: always
